DROP TABLE IF EXISTS API_KEY;
DROP TABLE IF EXISTS BLOG;
DROP TABLE IF EXISTS CONTACT;

CREATE TABLE API_KEY (
    ID  NUMBER NOT NULL,
    KEY VARCHAR (64) NOT NULL,
    PRIMARY KEY ("ID")
);


CREATE TABLE BLOG (
    ID          VARCHAR(64) NOT NULL,
    CATEGORY    VARCHAR(8) NOT NULL,
    TITLE       VARCHAR(128) NOT NULL,
    IMAGE       VARCHAR(128),
    INTRO       VARCHAR(512),
    DETAIL      VARCHAR NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ID")
);

CREATE TABLE CONTACT(
    ID          VARCHAR(64) NOT NULL,
    NAME        VARCHAR(64) NOT NULL,
    EMAIL       VARCHAR(64) NOT NULL,
    MESSENGER   VARCHAR NOT NULL,
    SENT_AT     TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY("ID")
)
